version: '3.8'
services:
  node:
    image: harold-node:v1.0
    container_name: harold-node
    build:
      dockerfile: Dockerfile
      context: ./node
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
    - '25674:25674'
    - '25676:25676'
      #    environment:
      #- NODE_HOST=node
      #- NODE_RPCPORT=6432
      #- NODE_SRVPORT=6433
    volumes:
      - /mnt/data/home/harold/data/:/root/.haroldcoin/
